# Generated by Django 3.1.7 on 2021-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMediaApp', '0002_auto_20210326_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginWithPhoneNumber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
