# Generated by Django 3.1.7 on 2021-03-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialMediaApp', '0005_auto_20210301_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoin',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='socialMediaApp.user'),
        ),
        migrations.AlterField(
            model_name='userjoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='socialMediaApp.user'),
        ),
    ]
