# Generated by Django 3.1.7 on 2021-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMediaApp', '0008_auto_20210301_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
