# Generated by Django 3.1.7 on 2021-03-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialMediaApp', '0011_auto_20210308_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likePost', to='socialMediaApp.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(error_messages={'unique': "You can't like a post twice."}, on_delete=django.db.models.deletion.CASCADE, related_name='likeUser', to='socialMediaApp.user', unique=True),
        ),
    ]
